### ISSUE TITLE
Got Assertion Error in assert len(ret) == 1, raw

### ISSUE THREAD

**Issue by thwu1** [Kaffaljidhmah2/Arxiv-Recommender#2]
`Traceback (most recent call last):
  File "/Users/xxx/arxiv/main.py", line 26, in <module>
    papers_dict = get_today_paper(cate_list=CATEGORY_LIST, is_save=IS_SAVE)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/arxiv/arxiv_util.py", line 101, in get_today_paper
    papers = list(decode_arxiv_webpage(arxiv_raw))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/arxiv/arxiv_util.py", line 64, in decode_arxiv_webpage
    assert len(ret) == 1, raw
AssertionError: &nbsp;  <span class="list-identifier"><a href="/abs/1312.7832" title="Abstract">arXiv:1312.7832</a> (cross-list from math.LO) [<a href="/pdf/1312.7832" title="Download PDF">pdf</a>, <a href="/ps/1312.7832" title="Download PostScript">ps</a>, <a href="/format/1312.7832" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Defining implication relation for classical logic
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/math?searchtype=author&query=Fu%2C+L">Li Fu</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> 33 pages; 2 tables
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Logic (math.LO)</span>; Artificial Intelligence (cs.AI); Computation and Language (cs.CL); Logic in Computer Science (cs.LO)

</div>
</div>

python main.py failed`

**Comment by thwu1** [comment]
Personally, I just use try, except to bypass this

**Comment by Kaffaljidhmah2** [comment]
Thank you for your bug report! The assertion error is caused by the following reason:

(1) in the pattern matching, I use (\d\d\d\d\.\d\d\d\d\d) to match arXiv ID. So the code anticipates 4 digits + one dot + 5 digits.
(2) this ancient paper was first released 10 years ago when the arXiv ID only had 4 digits + one dot + 4 digits. (LOL)
